baseURL = 'https://obsidiannotes.artefaktas.eu/'
languageCode = 'en-us'
title = 'Obsidian'
theme = 'hugo-paper'
ignoreFiles = ["/content/posts/templates.*","/content/posts/kanban/*","/content/posts/notion","/content/posts/wp_posts"]
disqusShortname = "obsidian-1"

[params]
  color = 'linen'
  avatar = 'https://www.dropbox.com/scl/fi/ifna6v5qr4bbgl0ovst1a/logo.jpg?rlkey=j7xax75606k6xmozierkpsh6k&st=avokba24&dl=1'
  github = 'Sparky4567'
  name = 'Artefaktas'
  bio = 'Freelance blogger and programmer'
  monoDarkIcon = true
  

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[menu]

  [[menu.main]]
    identifier = "main"
    name = "Main"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/tags/newpost/"
    weight = 2
  [[menu.main]]
    identifier = "contacts"
    name = "Contacts"
    url = "/page/contact/contact/"
    weight = 3
  [[menu.main]]
    identifier = "support"
    name = "Support"
    url = "/page/support/support/"
    weight = 4
  [[menu.main]]
    identifier = "privacy"
    name = "Privacy"
    url = "/page/privacy/privacy/"
    weight = 5
  [[menu.main]]
    identifier = "privacy"
    name = "Privacy"
    url = "/page/privacy/privacy/"
    weight = 6
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/page/about/about/"
    weight = 7
  [[menu.main]]
    identifier = "copyright"
    name = "Copyright"
    url = "/page/copyright/copyright/"
    weight = 8


[outputs]
  home = ["HTML", "RSS", "JSON"]
